// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StatProtos.proto

package yidian.data.meta.types;

public final class StatProtos {
  private StatProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(yidian.data.meta.types.StatProtos.aggType);
    registry.add(yidian.data.meta.types.StatProtos.defaultValue);
  }
  public interface StatValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yidian.data.meta.types.StatValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 cnt_vclick = 1;</code>
     */
    boolean hasCntVclick();
    /**
     * <code>optional int64 cnt_vclick = 1;</code>
     */
    long getCntVclick();

    /**
     * <code>optional int64 cnt_click = 2;</code>
     */
    boolean hasCntClick();
    /**
     * <code>optional int64 cnt_click = 2;</code>
     */
    long getCntClick();

    /**
     * <code>optional int64 cnt_view = 3;</code>
     */
    boolean hasCntView();
    /**
     * <code>optional int64 cnt_view = 3;</code>
     */
    long getCntView();

    /**
     * <code>optional int64 cnt_rview = 4;</code>
     */
    boolean hasCntRview();
    /**
     * <code>optional int64 cnt_rview = 4;</code>
     */
    long getCntRview();

    /**
     * <code>optional int64 cnt_like = 5;</code>
     */
    boolean hasCntLike();
    /**
     * <code>optional int64 cnt_like = 5;</code>
     */
    long getCntLike();

    /**
     * <code>optional int64 cnt_dislike = 6;</code>
     */
    boolean hasCntDislike();
    /**
     * <code>optional int64 cnt_dislike = 6;</code>
     */
    long getCntDislike();

    /**
     * <code>optional int64 cnt_share = 7;</code>
     */
    boolean hasCntShare();
    /**
     * <code>optional int64 cnt_share = 7;</code>
     */
    long getCntShare();

    /**
     * <code>optional int64 cnt_addcomment = 8;</code>
     */
    boolean hasCntAddcomment();
    /**
     * <code>optional int64 cnt_addcomment = 8;</code>
     */
    long getCntAddcomment();

    /**
     * <code>optional int64 cnt_thumbup = 9;</code>
     */
    boolean hasCntThumbup();
    /**
     * <code>optional int64 cnt_thumbup = 9;</code>
     */
    long getCntThumbup();

    /**
     * <code>optional int64 cnt_thumbdown = 10;</code>
     */
    boolean hasCntThumbdown();
    /**
     * <code>optional int64 cnt_thumbdown = 10;</code>
     */
    long getCntThumbdown();

    /**
     * <code>optional int64 cnt_dwell = 11;</code>
     */
    boolean hasCntDwell();
    /**
     * <code>optional int64 cnt_dwell = 11;</code>
     */
    long getCntDwell();

    /**
     * <code>optional int64 cnt_shortdwell = 12;</code>
     */
    boolean hasCntShortdwell();
    /**
     * <code>optional int64 cnt_shortdwell = 12;</code>
     */
    long getCntShortdwell();

    /**
     * <code>optional int64 dwell = 13;</code>
     */
    boolean hasDwell();
    /**
     * <code>optional int64 dwell = 13;</code>
     */
    long getDwell();

    /**
     * <code>optional int64 cmu_like = 14;</code>
     */
    boolean hasCmuLike();
    /**
     * <code>optional int64 cmu_like = 14;</code>
     */
    long getCmuLike();

    /**
     * <code>optional int64 cmu_addcomment = 15;</code>
     */
    boolean hasCmuAddcomment();
    /**
     * <code>optional int64 cmu_addcomment = 15;</code>
     */
    long getCmuAddcomment();

    /**
     * <code>optional int64 cmu_thumbup = 16;</code>
     */
    boolean hasCmuThumbup();
    /**
     * <code>optional int64 cmu_thumbup = 16;</code>
     */
    long getCmuThumbup();

    /**
     * <code>optional int64 cmu_thumbdown = 17;</code>
     */
    boolean hasCmuThumbdown();
    /**
     * <code>optional int64 cmu_thumbdown = 17;</code>
     */
    long getCmuThumbdown();

    /**
     * <code>optional int64 timestamp = 20;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 20;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code yidian.data.meta.types.StatValue}
   */
  public static final class StatValue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:yidian.data.meta.types.StatValue)
      StatValueOrBuilder {
    // Use StatValue.newBuilder() to construct.
    private StatValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StatValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StatValue defaultInstance;
    public static StatValue getDefaultInstance() {
      return defaultInstance;
    }

    public StatValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StatValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cntVclick_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cntClick_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              cntView_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              cntRview_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              cntLike_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              cntDislike_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              cntShare_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              cntAddcomment_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              cntThumbup_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              cntThumbdown_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              cntDwell_ = input.readInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              cntShortdwell_ = input.readInt64();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              dwell_ = input.readInt64();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              cmuLike_ = input.readInt64();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              cmuAddcomment_ = input.readInt64();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              cmuThumbup_ = input.readInt64();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              cmuThumbdown_ = input.readInt64();
              break;
            }
            case 160: {
              bitField0_ |= 0x00020000;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yidian.data.meta.types.StatProtos.internal_static_yidian_data_meta_types_StatValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yidian.data.meta.types.StatProtos.internal_static_yidian_data_meta_types_StatValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yidian.data.meta.types.StatProtos.StatValue.class, yidian.data.meta.types.StatProtos.StatValue.Builder.class);
    }

    public static com.google.protobuf.Parser<StatValue> PARSER =
        new com.google.protobuf.AbstractParser<StatValue>() {
      public StatValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StatValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StatValue> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CNT_VCLICK_FIELD_NUMBER = 1;
    private long cntVclick_;
    /**
     * <code>optional int64 cnt_vclick = 1;</code>
     */
    public boolean hasCntVclick() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 cnt_vclick = 1;</code>
     */
    public long getCntVclick() {
      return cntVclick_;
    }

    public static final int CNT_CLICK_FIELD_NUMBER = 2;
    private long cntClick_;
    /**
     * <code>optional int64 cnt_click = 2;</code>
     */
    public boolean hasCntClick() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 cnt_click = 2;</code>
     */
    public long getCntClick() {
      return cntClick_;
    }

    public static final int CNT_VIEW_FIELD_NUMBER = 3;
    private long cntView_;
    /**
     * <code>optional int64 cnt_view = 3;</code>
     */
    public boolean hasCntView() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 cnt_view = 3;</code>
     */
    public long getCntView() {
      return cntView_;
    }

    public static final int CNT_RVIEW_FIELD_NUMBER = 4;
    private long cntRview_;
    /**
     * <code>optional int64 cnt_rview = 4;</code>
     */
    public boolean hasCntRview() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 cnt_rview = 4;</code>
     */
    public long getCntRview() {
      return cntRview_;
    }

    public static final int CNT_LIKE_FIELD_NUMBER = 5;
    private long cntLike_;
    /**
     * <code>optional int64 cnt_like = 5;</code>
     */
    public boolean hasCntLike() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 cnt_like = 5;</code>
     */
    public long getCntLike() {
      return cntLike_;
    }

    public static final int CNT_DISLIKE_FIELD_NUMBER = 6;
    private long cntDislike_;
    /**
     * <code>optional int64 cnt_dislike = 6;</code>
     */
    public boolean hasCntDislike() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 cnt_dislike = 6;</code>
     */
    public long getCntDislike() {
      return cntDislike_;
    }

    public static final int CNT_SHARE_FIELD_NUMBER = 7;
    private long cntShare_;
    /**
     * <code>optional int64 cnt_share = 7;</code>
     */
    public boolean hasCntShare() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 cnt_share = 7;</code>
     */
    public long getCntShare() {
      return cntShare_;
    }

    public static final int CNT_ADDCOMMENT_FIELD_NUMBER = 8;
    private long cntAddcomment_;
    /**
     * <code>optional int64 cnt_addcomment = 8;</code>
     */
    public boolean hasCntAddcomment() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 cnt_addcomment = 8;</code>
     */
    public long getCntAddcomment() {
      return cntAddcomment_;
    }

    public static final int CNT_THUMBUP_FIELD_NUMBER = 9;
    private long cntThumbup_;
    /**
     * <code>optional int64 cnt_thumbup = 9;</code>
     */
    public boolean hasCntThumbup() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 cnt_thumbup = 9;</code>
     */
    public long getCntThumbup() {
      return cntThumbup_;
    }

    public static final int CNT_THUMBDOWN_FIELD_NUMBER = 10;
    private long cntThumbdown_;
    /**
     * <code>optional int64 cnt_thumbdown = 10;</code>
     */
    public boolean hasCntThumbdown() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 cnt_thumbdown = 10;</code>
     */
    public long getCntThumbdown() {
      return cntThumbdown_;
    }

    public static final int CNT_DWELL_FIELD_NUMBER = 11;
    private long cntDwell_;
    /**
     * <code>optional int64 cnt_dwell = 11;</code>
     */
    public boolean hasCntDwell() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int64 cnt_dwell = 11;</code>
     */
    public long getCntDwell() {
      return cntDwell_;
    }

    public static final int CNT_SHORTDWELL_FIELD_NUMBER = 12;
    private long cntShortdwell_;
    /**
     * <code>optional int64 cnt_shortdwell = 12;</code>
     */
    public boolean hasCntShortdwell() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int64 cnt_shortdwell = 12;</code>
     */
    public long getCntShortdwell() {
      return cntShortdwell_;
    }

    public static final int DWELL_FIELD_NUMBER = 13;
    private long dwell_;
    /**
     * <code>optional int64 dwell = 13;</code>
     */
    public boolean hasDwell() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int64 dwell = 13;</code>
     */
    public long getDwell() {
      return dwell_;
    }

    public static final int CMU_LIKE_FIELD_NUMBER = 14;
    private long cmuLike_;
    /**
     * <code>optional int64 cmu_like = 14;</code>
     */
    public boolean hasCmuLike() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int64 cmu_like = 14;</code>
     */
    public long getCmuLike() {
      return cmuLike_;
    }

    public static final int CMU_ADDCOMMENT_FIELD_NUMBER = 15;
    private long cmuAddcomment_;
    /**
     * <code>optional int64 cmu_addcomment = 15;</code>
     */
    public boolean hasCmuAddcomment() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int64 cmu_addcomment = 15;</code>
     */
    public long getCmuAddcomment() {
      return cmuAddcomment_;
    }

    public static final int CMU_THUMBUP_FIELD_NUMBER = 16;
    private long cmuThumbup_;
    /**
     * <code>optional int64 cmu_thumbup = 16;</code>
     */
    public boolean hasCmuThumbup() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional int64 cmu_thumbup = 16;</code>
     */
    public long getCmuThumbup() {
      return cmuThumbup_;
    }

    public static final int CMU_THUMBDOWN_FIELD_NUMBER = 17;
    private long cmuThumbdown_;
    /**
     * <code>optional int64 cmu_thumbdown = 17;</code>
     */
    public boolean hasCmuThumbdown() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional int64 cmu_thumbdown = 17;</code>
     */
    public long getCmuThumbdown() {
      return cmuThumbdown_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 20;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 20;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>optional int64 timestamp = 20;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      cntVclick_ = 0L;
      cntClick_ = 0L;
      cntView_ = 0L;
      cntRview_ = 0L;
      cntLike_ = 0L;
      cntDislike_ = 0L;
      cntShare_ = 0L;
      cntAddcomment_ = 0L;
      cntThumbup_ = 0L;
      cntThumbdown_ = 0L;
      cntDwell_ = 0L;
      cntShortdwell_ = 0L;
      dwell_ = 0L;
      cmuLike_ = 0L;
      cmuAddcomment_ = 0L;
      cmuThumbup_ = 0L;
      cmuThumbdown_ = 0L;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, cntVclick_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, cntClick_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, cntView_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, cntRview_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, cntLike_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, cntDislike_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, cntShare_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, cntAddcomment_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, cntThumbup_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, cntThumbdown_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, cntDwell_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt64(12, cntShortdwell_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt64(13, dwell_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt64(14, cmuLike_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt64(15, cmuAddcomment_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt64(16, cmuThumbup_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt64(17, cmuThumbdown_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeInt64(20, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, cntVclick_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, cntClick_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, cntView_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, cntRview_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, cntLike_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, cntDislike_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, cntShare_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, cntAddcomment_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, cntThumbup_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, cntThumbdown_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, cntDwell_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, cntShortdwell_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, dwell_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, cmuLike_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, cmuAddcomment_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(16, cmuThumbup_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(17, cmuThumbdown_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(20, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static yidian.data.meta.types.StatProtos.StatValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yidian.data.meta.types.StatProtos.StatValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yidian.data.meta.types.StatProtos.StatValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yidian.data.meta.types.StatProtos.StatValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yidian.data.meta.types.StatProtos.StatValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yidian.data.meta.types.StatProtos.StatValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static yidian.data.meta.types.StatProtos.StatValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static yidian.data.meta.types.StatProtos.StatValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static yidian.data.meta.types.StatProtos.StatValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yidian.data.meta.types.StatProtos.StatValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(yidian.data.meta.types.StatProtos.StatValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code yidian.data.meta.types.StatValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yidian.data.meta.types.StatValue)
        yidian.data.meta.types.StatProtos.StatValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yidian.data.meta.types.StatProtos.internal_static_yidian_data_meta_types_StatValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yidian.data.meta.types.StatProtos.internal_static_yidian_data_meta_types_StatValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yidian.data.meta.types.StatProtos.StatValue.class, yidian.data.meta.types.StatProtos.StatValue.Builder.class);
      }

      // Construct using yidian.data.meta.types.StatProtos.StatValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cntVclick_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        cntClick_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        cntView_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        cntRview_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        cntLike_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        cntDislike_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        cntShare_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        cntAddcomment_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        cntThumbup_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        cntThumbdown_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        cntDwell_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        cntShortdwell_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        dwell_ = 0L;
        bitField0_ = (bitField0_ & ~0x00001000);
        cmuLike_ = 0L;
        bitField0_ = (bitField0_ & ~0x00002000);
        cmuAddcomment_ = 0L;
        bitField0_ = (bitField0_ & ~0x00004000);
        cmuThumbup_ = 0L;
        bitField0_ = (bitField0_ & ~0x00008000);
        cmuThumbdown_ = 0L;
        bitField0_ = (bitField0_ & ~0x00010000);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00020000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yidian.data.meta.types.StatProtos.internal_static_yidian_data_meta_types_StatValue_descriptor;
      }

      public yidian.data.meta.types.StatProtos.StatValue getDefaultInstanceForType() {
        return yidian.data.meta.types.StatProtos.StatValue.getDefaultInstance();
      }

      public yidian.data.meta.types.StatProtos.StatValue build() {
        yidian.data.meta.types.StatProtos.StatValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public yidian.data.meta.types.StatProtos.StatValue buildPartial() {
        yidian.data.meta.types.StatProtos.StatValue result = new yidian.data.meta.types.StatProtos.StatValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cntVclick_ = cntVclick_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cntClick_ = cntClick_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cntView_ = cntView_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cntRview_ = cntRview_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cntLike_ = cntLike_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.cntDislike_ = cntDislike_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.cntShare_ = cntShare_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.cntAddcomment_ = cntAddcomment_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.cntThumbup_ = cntThumbup_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.cntThumbdown_ = cntThumbdown_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.cntDwell_ = cntDwell_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.cntShortdwell_ = cntShortdwell_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.dwell_ = dwell_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.cmuLike_ = cmuLike_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.cmuAddcomment_ = cmuAddcomment_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.cmuThumbup_ = cmuThumbup_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.cmuThumbdown_ = cmuThumbdown_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yidian.data.meta.types.StatProtos.StatValue) {
          return mergeFrom((yidian.data.meta.types.StatProtos.StatValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yidian.data.meta.types.StatProtos.StatValue other) {
        if (other == yidian.data.meta.types.StatProtos.StatValue.getDefaultInstance()) return this;
        if (other.hasCntVclick()) {
          setCntVclick(other.getCntVclick());
        }
        if (other.hasCntClick()) {
          setCntClick(other.getCntClick());
        }
        if (other.hasCntView()) {
          setCntView(other.getCntView());
        }
        if (other.hasCntRview()) {
          setCntRview(other.getCntRview());
        }
        if (other.hasCntLike()) {
          setCntLike(other.getCntLike());
        }
        if (other.hasCntDislike()) {
          setCntDislike(other.getCntDislike());
        }
        if (other.hasCntShare()) {
          setCntShare(other.getCntShare());
        }
        if (other.hasCntAddcomment()) {
          setCntAddcomment(other.getCntAddcomment());
        }
        if (other.hasCntThumbup()) {
          setCntThumbup(other.getCntThumbup());
        }
        if (other.hasCntThumbdown()) {
          setCntThumbdown(other.getCntThumbdown());
        }
        if (other.hasCntDwell()) {
          setCntDwell(other.getCntDwell());
        }
        if (other.hasCntShortdwell()) {
          setCntShortdwell(other.getCntShortdwell());
        }
        if (other.hasDwell()) {
          setDwell(other.getDwell());
        }
        if (other.hasCmuLike()) {
          setCmuLike(other.getCmuLike());
        }
        if (other.hasCmuAddcomment()) {
          setCmuAddcomment(other.getCmuAddcomment());
        }
        if (other.hasCmuThumbup()) {
          setCmuThumbup(other.getCmuThumbup());
        }
        if (other.hasCmuThumbdown()) {
          setCmuThumbdown(other.getCmuThumbdown());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yidian.data.meta.types.StatProtos.StatValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yidian.data.meta.types.StatProtos.StatValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long cntVclick_ ;
      /**
       * <code>optional int64 cnt_vclick = 1;</code>
       */
      public boolean hasCntVclick() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 cnt_vclick = 1;</code>
       */
      public long getCntVclick() {
        return cntVclick_;
      }
      /**
       * <code>optional int64 cnt_vclick = 1;</code>
       */
      public Builder setCntVclick(long value) {
        bitField0_ |= 0x00000001;
        cntVclick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_vclick = 1;</code>
       */
      public Builder clearCntVclick() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cntVclick_ = 0L;
        onChanged();
        return this;
      }

      private long cntClick_ ;
      /**
       * <code>optional int64 cnt_click = 2;</code>
       */
      public boolean hasCntClick() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 cnt_click = 2;</code>
       */
      public long getCntClick() {
        return cntClick_;
      }
      /**
       * <code>optional int64 cnt_click = 2;</code>
       */
      public Builder setCntClick(long value) {
        bitField0_ |= 0x00000002;
        cntClick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_click = 2;</code>
       */
      public Builder clearCntClick() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cntClick_ = 0L;
        onChanged();
        return this;
      }

      private long cntView_ ;
      /**
       * <code>optional int64 cnt_view = 3;</code>
       */
      public boolean hasCntView() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 cnt_view = 3;</code>
       */
      public long getCntView() {
        return cntView_;
      }
      /**
       * <code>optional int64 cnt_view = 3;</code>
       */
      public Builder setCntView(long value) {
        bitField0_ |= 0x00000004;
        cntView_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_view = 3;</code>
       */
      public Builder clearCntView() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cntView_ = 0L;
        onChanged();
        return this;
      }

      private long cntRview_ ;
      /**
       * <code>optional int64 cnt_rview = 4;</code>
       */
      public boolean hasCntRview() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 cnt_rview = 4;</code>
       */
      public long getCntRview() {
        return cntRview_;
      }
      /**
       * <code>optional int64 cnt_rview = 4;</code>
       */
      public Builder setCntRview(long value) {
        bitField0_ |= 0x00000008;
        cntRview_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_rview = 4;</code>
       */
      public Builder clearCntRview() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cntRview_ = 0L;
        onChanged();
        return this;
      }

      private long cntLike_ ;
      /**
       * <code>optional int64 cnt_like = 5;</code>
       */
      public boolean hasCntLike() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 cnt_like = 5;</code>
       */
      public long getCntLike() {
        return cntLike_;
      }
      /**
       * <code>optional int64 cnt_like = 5;</code>
       */
      public Builder setCntLike(long value) {
        bitField0_ |= 0x00000010;
        cntLike_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_like = 5;</code>
       */
      public Builder clearCntLike() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cntLike_ = 0L;
        onChanged();
        return this;
      }

      private long cntDislike_ ;
      /**
       * <code>optional int64 cnt_dislike = 6;</code>
       */
      public boolean hasCntDislike() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 cnt_dislike = 6;</code>
       */
      public long getCntDislike() {
        return cntDislike_;
      }
      /**
       * <code>optional int64 cnt_dislike = 6;</code>
       */
      public Builder setCntDislike(long value) {
        bitField0_ |= 0x00000020;
        cntDislike_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_dislike = 6;</code>
       */
      public Builder clearCntDislike() {
        bitField0_ = (bitField0_ & ~0x00000020);
        cntDislike_ = 0L;
        onChanged();
        return this;
      }

      private long cntShare_ ;
      /**
       * <code>optional int64 cnt_share = 7;</code>
       */
      public boolean hasCntShare() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 cnt_share = 7;</code>
       */
      public long getCntShare() {
        return cntShare_;
      }
      /**
       * <code>optional int64 cnt_share = 7;</code>
       */
      public Builder setCntShare(long value) {
        bitField0_ |= 0x00000040;
        cntShare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_share = 7;</code>
       */
      public Builder clearCntShare() {
        bitField0_ = (bitField0_ & ~0x00000040);
        cntShare_ = 0L;
        onChanged();
        return this;
      }

      private long cntAddcomment_ ;
      /**
       * <code>optional int64 cnt_addcomment = 8;</code>
       */
      public boolean hasCntAddcomment() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 cnt_addcomment = 8;</code>
       */
      public long getCntAddcomment() {
        return cntAddcomment_;
      }
      /**
       * <code>optional int64 cnt_addcomment = 8;</code>
       */
      public Builder setCntAddcomment(long value) {
        bitField0_ |= 0x00000080;
        cntAddcomment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_addcomment = 8;</code>
       */
      public Builder clearCntAddcomment() {
        bitField0_ = (bitField0_ & ~0x00000080);
        cntAddcomment_ = 0L;
        onChanged();
        return this;
      }

      private long cntThumbup_ ;
      /**
       * <code>optional int64 cnt_thumbup = 9;</code>
       */
      public boolean hasCntThumbup() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 cnt_thumbup = 9;</code>
       */
      public long getCntThumbup() {
        return cntThumbup_;
      }
      /**
       * <code>optional int64 cnt_thumbup = 9;</code>
       */
      public Builder setCntThumbup(long value) {
        bitField0_ |= 0x00000100;
        cntThumbup_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_thumbup = 9;</code>
       */
      public Builder clearCntThumbup() {
        bitField0_ = (bitField0_ & ~0x00000100);
        cntThumbup_ = 0L;
        onChanged();
        return this;
      }

      private long cntThumbdown_ ;
      /**
       * <code>optional int64 cnt_thumbdown = 10;</code>
       */
      public boolean hasCntThumbdown() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 cnt_thumbdown = 10;</code>
       */
      public long getCntThumbdown() {
        return cntThumbdown_;
      }
      /**
       * <code>optional int64 cnt_thumbdown = 10;</code>
       */
      public Builder setCntThumbdown(long value) {
        bitField0_ |= 0x00000200;
        cntThumbdown_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_thumbdown = 10;</code>
       */
      public Builder clearCntThumbdown() {
        bitField0_ = (bitField0_ & ~0x00000200);
        cntThumbdown_ = 0L;
        onChanged();
        return this;
      }

      private long cntDwell_ ;
      /**
       * <code>optional int64 cnt_dwell = 11;</code>
       */
      public boolean hasCntDwell() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int64 cnt_dwell = 11;</code>
       */
      public long getCntDwell() {
        return cntDwell_;
      }
      /**
       * <code>optional int64 cnt_dwell = 11;</code>
       */
      public Builder setCntDwell(long value) {
        bitField0_ |= 0x00000400;
        cntDwell_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_dwell = 11;</code>
       */
      public Builder clearCntDwell() {
        bitField0_ = (bitField0_ & ~0x00000400);
        cntDwell_ = 0L;
        onChanged();
        return this;
      }

      private long cntShortdwell_ ;
      /**
       * <code>optional int64 cnt_shortdwell = 12;</code>
       */
      public boolean hasCntShortdwell() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int64 cnt_shortdwell = 12;</code>
       */
      public long getCntShortdwell() {
        return cntShortdwell_;
      }
      /**
       * <code>optional int64 cnt_shortdwell = 12;</code>
       */
      public Builder setCntShortdwell(long value) {
        bitField0_ |= 0x00000800;
        cntShortdwell_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cnt_shortdwell = 12;</code>
       */
      public Builder clearCntShortdwell() {
        bitField0_ = (bitField0_ & ~0x00000800);
        cntShortdwell_ = 0L;
        onChanged();
        return this;
      }

      private long dwell_ ;
      /**
       * <code>optional int64 dwell = 13;</code>
       */
      public boolean hasDwell() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int64 dwell = 13;</code>
       */
      public long getDwell() {
        return dwell_;
      }
      /**
       * <code>optional int64 dwell = 13;</code>
       */
      public Builder setDwell(long value) {
        bitField0_ |= 0x00001000;
        dwell_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 dwell = 13;</code>
       */
      public Builder clearDwell() {
        bitField0_ = (bitField0_ & ~0x00001000);
        dwell_ = 0L;
        onChanged();
        return this;
      }

      private long cmuLike_ ;
      /**
       * <code>optional int64 cmu_like = 14;</code>
       */
      public boolean hasCmuLike() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int64 cmu_like = 14;</code>
       */
      public long getCmuLike() {
        return cmuLike_;
      }
      /**
       * <code>optional int64 cmu_like = 14;</code>
       */
      public Builder setCmuLike(long value) {
        bitField0_ |= 0x00002000;
        cmuLike_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cmu_like = 14;</code>
       */
      public Builder clearCmuLike() {
        bitField0_ = (bitField0_ & ~0x00002000);
        cmuLike_ = 0L;
        onChanged();
        return this;
      }

      private long cmuAddcomment_ ;
      /**
       * <code>optional int64 cmu_addcomment = 15;</code>
       */
      public boolean hasCmuAddcomment() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int64 cmu_addcomment = 15;</code>
       */
      public long getCmuAddcomment() {
        return cmuAddcomment_;
      }
      /**
       * <code>optional int64 cmu_addcomment = 15;</code>
       */
      public Builder setCmuAddcomment(long value) {
        bitField0_ |= 0x00004000;
        cmuAddcomment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cmu_addcomment = 15;</code>
       */
      public Builder clearCmuAddcomment() {
        bitField0_ = (bitField0_ & ~0x00004000);
        cmuAddcomment_ = 0L;
        onChanged();
        return this;
      }

      private long cmuThumbup_ ;
      /**
       * <code>optional int64 cmu_thumbup = 16;</code>
       */
      public boolean hasCmuThumbup() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional int64 cmu_thumbup = 16;</code>
       */
      public long getCmuThumbup() {
        return cmuThumbup_;
      }
      /**
       * <code>optional int64 cmu_thumbup = 16;</code>
       */
      public Builder setCmuThumbup(long value) {
        bitField0_ |= 0x00008000;
        cmuThumbup_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cmu_thumbup = 16;</code>
       */
      public Builder clearCmuThumbup() {
        bitField0_ = (bitField0_ & ~0x00008000);
        cmuThumbup_ = 0L;
        onChanged();
        return this;
      }

      private long cmuThumbdown_ ;
      /**
       * <code>optional int64 cmu_thumbdown = 17;</code>
       */
      public boolean hasCmuThumbdown() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional int64 cmu_thumbdown = 17;</code>
       */
      public long getCmuThumbdown() {
        return cmuThumbdown_;
      }
      /**
       * <code>optional int64 cmu_thumbdown = 17;</code>
       */
      public Builder setCmuThumbdown(long value) {
        bitField0_ |= 0x00010000;
        cmuThumbdown_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cmu_thumbdown = 17;</code>
       */
      public Builder clearCmuThumbdown() {
        bitField0_ = (bitField0_ & ~0x00010000);
        cmuThumbdown_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 20;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>optional int64 timestamp = 20;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 20;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00020000;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 20;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00020000);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:yidian.data.meta.types.StatValue)
    }

    static {
      defaultInstance = new StatValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:yidian.data.meta.types.StatValue)
  }

  public static final int AGG_TYPE_FIELD_NUMBER = 50002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> aggType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int DEFAULT_VALUE_FIELD_NUMBER = 50003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Long> defaultValue = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yidian_data_meta_types_StatValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yidian_data_meta_types_StatValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020StatProtos.proto\022\026yidian.data.meta.typ" +
      "es\032 google/protobuf/descriptor.proto\"\255\003\n" +
      "\tStatValue\022\037\n\ncnt_vclick\030\001 \001(\003B\013\222\265\030\003ADD\230" +
      "\265\030\000\022\021\n\tcnt_click\030\002 \001(\003\022\020\n\010cnt_view\030\003 \001(\003" +
      "\022\021\n\tcnt_rview\030\004 \001(\003\022\020\n\010cnt_like\030\005 \001(\003\022\023\n" +
      "\013cnt_dislike\030\006 \001(\003\022\021\n\tcnt_share\030\007 \001(\003\022\026\n" +
      "\016cnt_addcomment\030\010 \001(\003\022\023\n\013cnt_thumbup\030\t \001" +
      "(\003\022\025\n\rcnt_thumbdown\030\n \001(\003\022\021\n\tcnt_dwell\030\013" +
      " \001(\003\022\026\n\016cnt_shortdwell\030\014 \001(\003\022\r\n\005dwell\030\r " +
      "\001(\003\022\032\n\010cmu_like\030\016 \001(\003B\010\222\265\030\004LAST\022 \n\016cmu_a",
      "ddcomment\030\017 \001(\003B\010\222\265\030\004LAST\022\035\n\013cmu_thumbup" +
      "\030\020 \001(\003B\010\222\265\030\004LAST\022\037\n\rcmu_thumbdown\030\021 \001(\003B" +
      "\010\222\265\030\004LAST\022\021\n\ttimestamp\030\024 \001(\003:1\n\010agg_type" +
      "\022\035.google.protobuf.FieldOptions\030\322\206\003 \001(\t:" +
      "6\n\rdefault_value\022\035.google.protobuf.Field" +
      "Options\030\323\206\003 \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_yidian_data_meta_types_StatValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yidian_data_meta_types_StatValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yidian_data_meta_types_StatValue_descriptor,
        new java.lang.String[] { "CntVclick", "CntClick", "CntView", "CntRview", "CntLike", "CntDislike", "CntShare", "CntAddcomment", "CntThumbup", "CntThumbdown", "CntDwell", "CntShortdwell", "Dwell", "CmuLike", "CmuAddcomment", "CmuThumbup", "CmuThumbdown", "Timestamp", });
    aggType.internalInit(descriptor.getExtensions().get(0));
    defaultValue.internalInit(descriptor.getExtensions().get(1));
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(yidian.data.meta.types.StatProtos.aggType);
    registry.add(yidian.data.meta.types.StatProtos.defaultValue);
    registry.add(yidian.data.meta.types.StatProtos.aggType);
    registry.add(yidian.data.meta.types.StatProtos.aggType);
    registry.add(yidian.data.meta.types.StatProtos.aggType);
    registry.add(yidian.data.meta.types.StatProtos.aggType);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
